services:
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  backend:
    image: "ajax/backend"
    environment: 
      DB_TRUST: "true"
      DB_ADDRESS: "database"
      DB_PORT: "1433"
      DB_USER: "sa"
      DB_PASSWORD: "Your_password123"
      DB_NAME: "blogging"
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on: database
    
  frontend:
    image: "ajax/frontend"
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: frontend/proxy.Dockerfile
    depends_on: backend