apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajax-database-pod
  labels:
    app: ajax-database-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajax-database-pod
  template:
    metadata:
      name: ajax-database-pod
      labels:
        app: ajax-database-pod
    spec:
      containers:
        - name: ajax-database-pod
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
      restartPolicy: Always
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: ajax-database
spec:
  selector:
    app: ajax-database-pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer