apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajax-frontend-pod
  labels:
    app: ajax-frontend-pod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ajax-frontend-pod
  template:
    metadata:
      name: ajax-frontend-pod
      labels:
        app: ajax-frontend-pod
    spec:
      containers:
        - name: ajax-frontend-pod
          image: docker.io/marcinator/ajax-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_TRUST
              value: "true"
            - name: DB_ADDRESS
              value: "database"
            - name: DB_PORT
              value: "1433"
            - name: DB_NAME
              value: "blogging"
            - name: DB_USER
              value: "sa"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
      restartPolicy: Always
        
---  
apiVersion: v1
kind: Service
metadata:
  name: ajax-frontend
spec:
  selector:
    app: ajax-frontend-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort